### PR TITLE
Feature/alexander/final eth test

### PR DESCRIPTION
**Pull request by xand6r**
### What does this PR do?
- This PR creates an API which serves as a link between the blockchain and the frontend

#### Description of Task to be completed?
- Add an API to get all elections

#### How should this be manually tested?
- Clone the repo [vote-right-backend](https://github.com/Enye-Team-Giraffe/vote-right-backend)
- cd `vote-right-backend`
-  `npm install`
-  `npm test` on your terminal

#### Checklist:
- [x] add an endpoint to view all elections

#### Stories?
- N/A

#### Screenshots (if appropriate)
- N/A

#### Questions:
- N/A

### CODE REVIEW

**Comment by xand6r** [comment]
[Create the api's interacting with the blockchain on nodejs](https://trello.com/c/W06M4g9h/60-create-the-apis-interacting-with-the-blockchain-on-nodejs)

**Comment by xand6r** [comment]
[Create the api's interacting with the blockchain on nodejs](https://trello.com/c/W06M4g9h/60-create-the-apis-interacting-with-the-blockchain-on-nodejs)

**Comment by xand6r** [comment]
[integrate this contract into the backend using web3 and hdwallet](https://trello.com/c/vMWrMZT9/59-integrate-this-contract-into-the-backend-using-web3-and-hdwallet)

**Review by usmanoa — APPROVED** [review]
Looks good

**Comment by xand6r** [comment]
[Admin should be able to interact with smart contract on the block-chain via an API](https://trello.com/c/5mXHwRET/63-admin-should-be-able-to-interact-with-smart-contract-on-the-block-chain-via-an-api)

**Pull request merged**
